version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_notifications_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3320:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql