server:
  port: 9013

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # USERS SERVICE
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/user-profiles/**,/api/v1/patient-profiles/**,/api/v1/receptionist-profiles/**,/api/v1/administrator-profiles/**

        # DOCTORS SERVICE
        - id: doctors-service
          uri: lb://doctors-service
          predicates:
            - Path=/api/v2/doctors/**

        # SPECIALTIES SERVICE
        - id: specialties-service
          uri: lb://specialties-service
          predicates:
            - Path=/api/v1/specialties/**

        # SCHEDULE SERVICE
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/api/v1/doctor-schedules/**,/api/v1/doctor-time-off/**,/api/v1/schedule-slots/**

        # APPOINTMENTS SERVICE
        - id: appointments-service
          uri: lb://appointments-service
          predicates:
            - Path=/api/v1/appointments/**

        # PAYMENTS SERVICE
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/api/payments/**

        # MEDICAL RECORDS SERVICE
        - id: medical-records-service
          uri: lb://medical-records-service
          predicates:
            - Path=/api/v1/medical-records/**,/api/v1/medical-visit/**,/api/v1/diagnoses/**,/api/v1/vital-signs/**

        # PRESCRIPTIONS SERVICE
        - id: prescriptions-service
          uri: lb://prescriptions-service
          predicates:
            - Path=/api/v1/prescriptions/**,/api/v1/prescription-items/**

        # NOTIFICATIONS SERVICE
        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/v1/notifications/**,/api/v1/notification-templates/**

        # REPORTS SERVICE
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/api/v1/reports-request/**,/api/v1/generated-reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
