version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_medical_records_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical_records_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3318:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
